### Index method

GET http://localhost:3000/api/locations

### succesfully posts a location 


POST http://localhost:3000/api/locations
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE4MTI2NzYsInN1YiI6M30.lQ-PUKdLrlYLhQNiDgqq00qr37pgFIp-Sjw8Iirsw4Q

{
    "user_id": 2,
    "location_type_id":3,
    "name":"testarooni",
    "address": "123 fakestreet" ,
    "description":"A fun dogpark for all to come and play!"
}

### unseccesfull request

POST http://localhost:3000/api/locations
Content-Type: application/json

{
    "location_type_id":3,
    "name":"testarooni",
    "address": "123 fakestreet" ,
    "rating": 4
}

### show location id 1
GET http://localhost:3000/api/locations/1

### unsuccessful location show
GET http://localhost:3000/api/locations/100


### succesfull location update
PUT http://localhost:3000/api/locations/1
Content-Type: application/json

{
    "name":"KCC Dog park"
}

### Delete method works

DELETE http://localhost:3000/api/locations/1

### Delete method wont delete if the location doesnt exist

DELETE http://localhost:3000/api/locations/1000


####################################################
########### Begin User tests########################
####################################################

### Create User run twice to check validations

POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
"user":
{
    "username":"testyboi",
    "email":"test@me.com",
    "password":"testme",
    "password_confirmation":"testme"
    
}

}

### Check user can sign in after sign up
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
"user":
{
    "email":"test@me.com",
    "password":"testme"
    
}
}


### Check user can't sing in with incorect details
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
"user":
{
    "email":"test@me.com",
    "password":"testme2"
    
}
}